# Generated by Django 3.2.3 on 2021-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=20, verbose_name='게시판 제목')),
                ('board_contents', models.TextField(verbose_name='내용')),
                ('board_views', models.IntegerField(default=0, verbose_name='조회수')),
                ('board_create_at', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('board_type', models.CharField(max_length=30, verbose_name='게시판 타입')),
                ('board_like', models.IntegerField(default=0, verbose_name='추천수')),
            ],
            options={
                'db_table': 'board',
                'ordering': ['-board_create_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_int', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=100, verbose_name='댓글 내용')),
                ('comment_writer', models.CharField(max_length=30, verbose_name='댓글 작성자')),
                ('board_create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 날짜')),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=30, verbose_name='사용자 이메일')),
                ('user_pwd', models.CharField(max_length=255, verbose_name='사용자 비밀번호')),
                ('user_nickname', models.CharField(max_length=30, verbose_name='사용자 닉네임')),
                ('user_subscription', models.CharField(max_length=30, null=True, verbose_name='사용자 가입경로')),
                ('users_skin_type', models.CharField(max_length=30, null=True, verbose_name='사용자 피부톤')),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
